## This file was auto-generated by CloudCoreo CLI
## This file was automatically generated using the CloudCoreo CLI
##
## This config.rb file exists to create and maintain services not related to compute.
## for example, a VPC might be maintained using:
##
## coreo_aws_vpc_vpc "my-vpc" do
##   action :sustain
##   cidr "12.0.0.0/16"
##   internet_gateway true
## end
##


# TEMPORARY - COPY THESE FROM BASE STACK SO THEY DONT GET OVERRIDDEN
#
coreo_aws_vpc_subnet "foo" do
  action :sustain
  send_on "change"
  number_of_zones 2
  percent_of_vpc_allocated 25
  route_table "foo"
  vpc "foo"
  map_public_ip_on_launch true
  regions "TBS"
end
